version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
    - checkout
    # copied from Vampire (https://discuss.circleci.com/t/recommended-dependencies-caching-for-a-gradle-setup-is-wrong/20712/3)
    - restore_cache:
        keys:
        - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

    - restore_cache:
        keys:
        - gradle-cache-{{ checksum "build.gradle" }}
        - gradle-cache

    - restore_cache:
        keys:
        - gradle-build-caches-{{ .Revision }}
        - gradle-build-caches

    - run:
        name: Restoring Gradle Build Caches
        command: |
          [ -d ~/gradle-build-caches ] &&
            [ -n "$(ls -A ~/gradle-build-caches)" ] &&
            rm -rf ~/.gradle/caches/build-cache-* &&
            mv ~/gradle-build-caches/* ~/.gradle/caches/ || true

    # download and cache dependencies and Gradle
    - run:
        name: Downloading Dependencies
        command: ./gradlew --max-workers 2 downloadDependencies

    - save_cache:
        paths:
        - ~/.gradle/wrapper/
        key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

    - save_cache:
        paths:
        - ~/.gradle/caches/
        key: gradle-cache-{{ checksum "build.gradle" }}

    # build everything needed for publication
    - run:
        name: Building Project
        command: ./gradlew --max-workers 2 --continue build

    # cache gradle build caches
    - run:
        name: Collecting Gradle Build Caches
        command: |
          mkdir -p ~/gradle-build-caches
          [ -d ~/.gradle/caches ] &&
            [ -n "$(ls -Ad ~/.gradle/caches/build-cache-* 2>/dev/null)" ] &&
            mv ~/.gradle/caches/build-cache-* ~/gradle-build-caches || true
        when: always

    - save_cache:
        paths:
        - ~/gradle-build-caches
        key: gradle-build-caches-{{ .Revision }}
        when: always